name: Laravel Brazilian Ceps

on:
  pull_request:
    branches: [ main, dev, v1.x-dev ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Laravel 9 supports PHP 8.1–8.2
          - php: 8.1
            laravel: 9.*
          - php: 8.2
            laravel: 9.*

          # Laravel 10 supports PHP 8.1–8.3
          - php: 8.1
            laravel: 10.*
          - php: 8.2
            laravel: 10.*
          - php: 8.3
            laravel: 10.*

          # Laravel 11 supports PHP 8.2–8.4
          - php: 8.2
            laravel: 11.*
          - php: 8.3
            laravel: 11.*
          - php: 8.4
            laravel: 11.*

          # Laravel 12 supports PHP 8.2–8.4
          - php: 8.2
            laravel: 12.*
          - php: 8.3
            laravel: 12.*
          - php: 8.4
            laravel: 12.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo, openssl, json, imagick, swoole, sqlite3
          coverage: none

      - name: Validate PHP and Composer
        run: |
          php -v
          composer -V
          composer validate

      - name: Configure Laravel Version
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" \
                           "illuminate/encryption:${{ matrix.laravel }}" \
                           "illuminate/http:${{ matrix.laravel }}" \
                           --no-interaction --no-update

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: composer test
